(package "shiwake-mode" "0.1.0" "Major mode for editing shiwake files.")
(website-url "https://github.com/tateishi/shiwake-mode")
(keywords "convenience" "files" "tools")

(source "gnu")
(source "melpa")

(package-file "shiwake-mode.el")

(depends-on "emacs" "28.1")
(depends-on "ledger-mode")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
